Cherry-pick commit d98a6f557c4a677bcf7f40f1d22c0f1f96e750d3 to resolve error cannot login when deploy branch pj/at/release_ver4
error: "the cache for 'nts.uk.ctx.bs.employee.app.cache.employment.EmploymentInfoCache' not prepared"